### ISSUE TITLE
0.0.16 release?

### ISSUE THREAD

**Issue by bkmeneguello** [avarabyeu/jashing#8]
Any plans to release a new revision?

**Comment by avarabyeu** [comment]
hi @bkmeneguello. Do you need smth additional to be included into the 0.0.16 or you OK with current master?

**Comment by bkmeneguello** [comment]
There is one PR pending to match my current production status. If you can accept it, it's ok for me. Thanks!

**Comment by bkmeneguello** [comment]
bump

**Comment by avarabyeu** [comment]
@bkmeneguello oh, sorry missed the answer. sure, let me make new release

**Comment by bkmeneguello** [comment]
bump

**Comment by bkmeneguello** [comment]
bump

**Comment by avarabyeu** [comment]
@bkmeneguello oh, sorry. Will do today

**Comment by bkmeneguello** [comment]
today?

**Comment by avarabyeu** [comment]
@bkmeneguello sorry for the delay and thank you for the notification. I've just pushed new version (0.0.16) to maven central. Should be available in several hours.

**Comment by bkmeneguello** [comment]
Thank you very much!
